### PR TITLE
Remove title assets

### PR DESCRIPTION
**Pull request by MCAlagaesia**
The title assets alone are over half the size of the entire server resource pack, making server resource pack downloading unnecessarily slow. Since they don't add anything to the game, they can be removed.

image

### CODE REVIEW

**Comment by VoidShadow204** [comment]
To be honest, I like the background, and I was thinking about an updating now and then featuring a new location we finished.
But if it slows down the down, I can remove it.

**Comment by MCAlagaesia** [comment]
You can't even see the background because server resource packs aren't available on the client in the title screen.

Happy to merge?

**Comment by VoidShadow204** [comment]
Yeah, this is true lol. I am using the offline version, for editing the GitHub source. Yeah, you can just remove them, I am fine. I think, there will be no background like this in the new Launcher?

**Comment by MCAlagaesia** [comment]
We'll have to work that out with the developers.

**Pull request merged**
